server:
  port: 8888


#spring
spring:
  datasource:
    url: jdbc:mysql://localhost/community?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

##github≈‰÷√–≈–ƒ
github:
  client:
    id: 42e591d46be31af9c854
    secret: ee51a20d4185d65a1bfba0825f94daacaa9b1656
    callback: http://localhost:8888/callback

